services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
       - ./client:/client
  web-server:
    build:
      context: ./server/web-server
      dockerfile: Dockerfile.dev
    ports:
       - "3000:3000"
       - "8000:8000"
    volumes:
       - ./server/web-server:/web-server
  notification-service:
    build:
      context: ./server/notification-service
      dockerfile: Dockerfile.dev
    ports:
       - "8080:8080"
    volumes:
       - ./server/notification-service:/notification-service
    depends_on:
      - web-server
