services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
       - ./client:/client
  web-server:
    build:
      context: ./server/web-server
      dockerfile: Dockerfile.dev
    ports:
       - "3000:3000"
       - "8000:8000"
    volumes:
       - ./server/web-server:/web-server
